### ISSUE TITLE
event list activity

### ISSUE THREAD

**Issue by spxrogers** [spxrogers/UTimeline#6]
needs custom text view input followed by list/recycler view of preset events (stored in res/arrays.xml possibly?)

usage we agreed on (to my recollection, correct me if wrong): the event is chosen either on a) a tap from the preset list or b) after the user dismisses the keyboard and the title is whatever is the active text inputted upon dismissal. the activity stack then auto pops back with the title now set.

**Comment by wibergln** [comment]
Plan:
1. Add arrays.xml to res/values/
   - Add event array to the xml file with names of the pre-set events
2. Create a layout file for event list
   - A text view input, pre-populated with something like "_Add custom event..._"
   - A list view, to be populated with the values from the array
3. Add logic
   - Clicking a text view input will automatically bring up the keyboard. When the user dismisses the keyboard, return the entered value to the previous activity so that the title can be filled in
   - set the list view item's onClick to return the value (event name) of that item to the previous activity so that the title can be filled in
